###
GET http://localhost:8000/business/admin/daily-train-ticket/query-list?page=1&size=5&trainCode=G1&start=北京&end=南京
Content-Type: application/json
###
GET http://localhost:8000/business/admin/daily-train-ticket/query-list2?page=3&size=5&trainCode=G1&start=北京&end=南京
Content-Type: application/json
###