###
POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3NTE3OTMzMzcsIm1vYmlsZSI6IjEzMDAwMDAwMDAwIiwiaWQiOjE5MDkyMTk2ODE4NDQyMDM1MjAsImV4cCI6MTc1MTg3OTczNywiaWF0IjoxNzUxNzkzMzM3fQ.u8n-SPAmkvhzgcehHt3zoVeXN7QVR8LQk98odG19H0w

{
  "dailyTrainTicketId":1941788276683837440,
  "date":1751472000000,
  "end":"上海",
  "start":"北京",
  "tickets":[{
    "passengerId":1913511730294689792,
    "passengerName":"睡睡",
    "passengerType":"2",
    "seatTypeCode":"1"
  }],
  "trainCode":"G1"
}
###
