###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "李四",
  "idCard": "123245",
  "type": "2"
}

###

GET http://localhost:8000/member/passenger/query-list?page=1&size=3
Accept: application/json
token: {{token}}

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1913465699125301248,
  "memberId": 1909219681844203520,
  "name": "41911",
  "idCard": "123245",
  "type": "2"
}

###